/****************************************************************
   This file was created automatically by `FlexCat 2.19'
   from "/home/willem/ApolloOS/workbench/prefs/printer/catalogs/printer.cd".

   Do NOT edit by hand!
****************************************************************/

#ifndef PRINTER_STRINGS_H
#define PRINTER_STRINGS_H


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif


#ifdef CATCOMP_ARRAY
#ifndef CATCOMPARRAY
#define CATCOMPARRAY CatCompArray
#endif
#undef CATCOMP_NUMBERS
#undef CATCOMP_STRINGS
#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS
#endif

#ifdef CATCOMP_BLOCK
#undef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif

/***************************************************************/

#ifdef CATCOMP_NUMBERS

#define MSG_WINTITLE 0
#define MSG_OK 1
#define MSG_PRINTER_DRIVER 2
#define MSG_PRINTER_SETTINGS 3
#define MSG_PRINTER_SELECT_DRIVER 4
#define MSG_PRINTER_NAME 5
#define MSG_PRINTER_UNIT 6
#define MSG_PRINTER_PS_UNIT 7
#define MSG_PRINTER_CUSTOM_DEVICE 8
#define MSG_PRINTER_DEVICE_UNIT 9
#define MSG_PRINTER_PARALLEL 10
#define MSG_PRINTER_SERIAL 11
#define MSG_PRINTER_TO_FILE 12
#define MSG_PRINTER_USB 13
#define MSG_TISK_PAPER_TYPE 14
#define MSG_TISK_PAPER_SIZE 15
#define MSG_TISK_QUALITY 16
#define MSG_TISK_PITCH 17
#define MSG_TISK_SPACING 18
#define MSG_TISK_LEFT_MARGIN 19
#define MSG_TISK_RIGHT_MARGIN 20
#define MSG_TISK_LINE_PER_PAGE 21
#define MSG_TISK_DENSITY 22
#define MSG_TISK_ASPECT 23
#define MSG_TISK_SHADE 24
#define MSG_TISK_IMAGE 25
#define MSG_TISK_TRESHOLD 26
#define MSG_TISK_DITHERING 27
#define MSG_TISK_DIMENSION 28
#define MSG_TISK_PAPER_OFFSET 29
#define MSG_TISK_CENTER_IMAGE 30
#define MSG_TISK_ANTIALIAS 31
#define MSG_TISK_INTEGER_SCALING 32
#define MSG_TISK_FANFOLD 33
#define MSG_TISK_SINGLE 34
#define MSG_TISK_DRAFT 35
#define MSG_TISK_LETTER 36
#define MSG_TISK_PORTRAIT 37
#define MSG_TISK_LANDSCAPE 38
#define MSG_TISK_BW 39
#define MSG_TISK_GRAY 40
#define MSG_TISK_COLOR 41
#define MSG_TISK_GRAY2 42
#define MSG_TISK_POSITIVE 43
#define MSG_TISK_NEGATIVE 44
#define MSG_TISK_IGNORE 45
#define MSG_TISK_BOUNDED 46
#define MSG_TISK_ABSOLUTE 47
#define MSG_TISK_PIXEL 48
#define MSG_TISK_MULTIPLY 49
#define MSG_TISK_ORDERED 50
#define MSG_TISK_HALFTONE 51
#define MSG_TISK_FLOYDSTEINBERG 52

#endif /* CATCOMP_NUMBERS */

/***************************************************************/

#ifdef CATCOMP_STRINGS

#define MSG_WINTITLE_STR "Printer Preferences"
#define MSG_OK_STR "Ok"
#define MSG_PRINTER_DRIVER_STR "Driver"
#define MSG_PRINTER_SETTINGS_STR "Settings"
#define MSG_PRINTER_SELECT_DRIVER_STR "Select Driver:"
#define MSG_PRINTER_NAME_STR "Name:"
#define MSG_PRINTER_UNIT_STR "Printer Unit:"
#define MSG_PRINTER_PS_UNIT_STR "Unit:"
#define MSG_PRINTER_CUSTOM_DEVICE_STR "Custom device:"
#define MSG_PRINTER_DEVICE_UNIT_STR "Unit %d"
#define MSG_PRINTER_PARALLEL_STR "Parallel"
#define MSG_PRINTER_SERIAL_STR "Serial"
#define MSG_PRINTER_TO_FILE_STR "Print to file"
#define MSG_PRINTER_USB_STR "USB Printer"
#define MSG_TISK_PAPER_TYPE_STR "Paper Type:"
#define MSG_TISK_PAPER_SIZE_STR "Paper Size:"
#define MSG_TISK_QUALITY_STR "Quality:"
#define MSG_TISK_PITCH_STR "Pitch:"
#define MSG_TISK_SPACING_STR "Spacing:"
#define MSG_TISK_LEFT_MARGIN_STR "Left Margin:"
#define MSG_TISK_RIGHT_MARGIN_STR "Right Margin:"
#define MSG_TISK_LINE_PER_PAGE_STR "Lines per Page:"
#define MSG_TISK_DENSITY_STR "Density:"
#define MSG_TISK_ASPECT_STR "Aspect:"
#define MSG_TISK_SHADE_STR "Shade:"
#define MSG_TISK_IMAGE_STR "Image:"
#define MSG_TISK_TRESHOLD_STR "Threshold:"
#define MSG_TISK_DITHERING_STR "Dithering:"
#define MSG_TISK_DIMENSION_STR "Dimensions:"
#define MSG_TISK_PAPER_OFFSET_STR "Offset ("
#define MSG_TISK_CENTER_IMAGE_STR "Center Image:"
#define MSG_TISK_ANTIALIAS_STR "AntiAlias:"
#define MSG_TISK_INTEGER_SCALING_STR "Integer Scaling:"
#define MSG_TISK_FANFOLD_STR "Fanfold"
#define MSG_TISK_SINGLE_STR "Single"
#define MSG_TISK_DRAFT_STR "Draft (72 dpi)"
#define MSG_TISK_LETTER_STR "Letter (240 dpi)"
#define MSG_TISK_PORTRAIT_STR "Portrait"
#define MSG_TISK_LANDSCAPE_STR "Landscape"
#define MSG_TISK_BW_STR "Black & White"
#define MSG_TISK_GRAY_STR "Greyscape"
#define MSG_TISK_COLOR_STR "Color"
#define MSG_TISK_GRAY2_STR "Greyscape 2"
#define MSG_TISK_POSITIVE_STR "Positive"
#define MSG_TISK_NEGATIVE_STR "Negative"
#define MSG_TISK_IGNORE_STR "Ignore"
#define MSG_TISK_BOUNDED_STR "Bounded"
#define MSG_TISK_ABSOLUTE_STR "Absolute"
#define MSG_TISK_PIXEL_STR "Pixel"
#define MSG_TISK_MULTIPLY_STR "Multiply"
#define MSG_TISK_ORDERED_STR "Ordered"
#define MSG_TISK_HALFTONE_STR "Halftone"
#define MSG_TISK_FLOYDSTEINBERG_STR "Floyd-Steinberg"

#endif /* CATCOMP_STRINGS */

/***************************************************************/

#ifdef CATCOMP_ARRAY

#ifndef HAVE_CATCOMP_ARRAYTYPE
#define HAVE_CATCOMP_ARRAYTYPE
struct CatCompArrayType
{
  IPTR   cca_ID;
  STRPTR cca_Str;
};
#endif

static const struct CatCompArrayType CATCOMPARRAY[] =
{
  {MSG_WINTITLE,(STRPTR)MSG_WINTITLE_STR},
  {MSG_OK,(STRPTR)MSG_OK_STR},
  {MSG_PRINTER_DRIVER,(STRPTR)MSG_PRINTER_DRIVER_STR},
  {MSG_PRINTER_SETTINGS,(STRPTR)MSG_PRINTER_SETTINGS_STR},
  {MSG_PRINTER_SELECT_DRIVER,(STRPTR)MSG_PRINTER_SELECT_DRIVER_STR},
  {MSG_PRINTER_NAME,(STRPTR)MSG_PRINTER_NAME_STR},
  {MSG_PRINTER_UNIT,(STRPTR)MSG_PRINTER_UNIT_STR},
  {MSG_PRINTER_PS_UNIT,(STRPTR)MSG_PRINTER_PS_UNIT_STR},
  {MSG_PRINTER_CUSTOM_DEVICE,(STRPTR)MSG_PRINTER_CUSTOM_DEVICE_STR},
  {MSG_PRINTER_DEVICE_UNIT,(STRPTR)MSG_PRINTER_DEVICE_UNIT_STR},
  {MSG_PRINTER_PARALLEL,(STRPTR)MSG_PRINTER_PARALLEL_STR},
  {MSG_PRINTER_SERIAL,(STRPTR)MSG_PRINTER_SERIAL_STR},
  {MSG_PRINTER_TO_FILE,(STRPTR)MSG_PRINTER_TO_FILE_STR},
  {MSG_PRINTER_USB,(STRPTR)MSG_PRINTER_USB_STR},
  {MSG_TISK_PAPER_TYPE,(STRPTR)MSG_TISK_PAPER_TYPE_STR},
  {MSG_TISK_PAPER_SIZE,(STRPTR)MSG_TISK_PAPER_SIZE_STR},
  {MSG_TISK_QUALITY,(STRPTR)MSG_TISK_QUALITY_STR},
  {MSG_TISK_PITCH,(STRPTR)MSG_TISK_PITCH_STR},
  {MSG_TISK_SPACING,(STRPTR)MSG_TISK_SPACING_STR},
  {MSG_TISK_LEFT_MARGIN,(STRPTR)MSG_TISK_LEFT_MARGIN_STR},
  {MSG_TISK_RIGHT_MARGIN,(STRPTR)MSG_TISK_RIGHT_MARGIN_STR},
  {MSG_TISK_LINE_PER_PAGE,(STRPTR)MSG_TISK_LINE_PER_PAGE_STR},
  {MSG_TISK_DENSITY,(STRPTR)MSG_TISK_DENSITY_STR},
  {MSG_TISK_ASPECT,(STRPTR)MSG_TISK_ASPECT_STR},
  {MSG_TISK_SHADE,(STRPTR)MSG_TISK_SHADE_STR},
  {MSG_TISK_IMAGE,(STRPTR)MSG_TISK_IMAGE_STR},
  {MSG_TISK_TRESHOLD,(STRPTR)MSG_TISK_TRESHOLD_STR},
  {MSG_TISK_DITHERING,(STRPTR)MSG_TISK_DITHERING_STR},
  {MSG_TISK_DIMENSION,(STRPTR)MSG_TISK_DIMENSION_STR},
  {MSG_TISK_PAPER_OFFSET,(STRPTR)MSG_TISK_PAPER_OFFSET_STR},
  {MSG_TISK_CENTER_IMAGE,(STRPTR)MSG_TISK_CENTER_IMAGE_STR},
  {MSG_TISK_ANTIALIAS,(STRPTR)MSG_TISK_ANTIALIAS_STR},
  {MSG_TISK_INTEGER_SCALING,(STRPTR)MSG_TISK_INTEGER_SCALING_STR},
  {MSG_TISK_FANFOLD,(STRPTR)MSG_TISK_FANFOLD_STR},
  {MSG_TISK_SINGLE,(STRPTR)MSG_TISK_SINGLE_STR},
  {MSG_TISK_DRAFT,(STRPTR)MSG_TISK_DRAFT_STR},
  {MSG_TISK_LETTER,(STRPTR)MSG_TISK_LETTER_STR},
  {MSG_TISK_PORTRAIT,(STRPTR)MSG_TISK_PORTRAIT_STR},
  {MSG_TISK_LANDSCAPE,(STRPTR)MSG_TISK_LANDSCAPE_STR},
  {MSG_TISK_BW,(STRPTR)MSG_TISK_BW_STR},
  {MSG_TISK_GRAY,(STRPTR)MSG_TISK_GRAY_STR},
  {MSG_TISK_COLOR,(STRPTR)MSG_TISK_COLOR_STR},
  {MSG_TISK_GRAY2,(STRPTR)MSG_TISK_GRAY2_STR},
  {MSG_TISK_POSITIVE,(STRPTR)MSG_TISK_POSITIVE_STR},
  {MSG_TISK_NEGATIVE,(STRPTR)MSG_TISK_NEGATIVE_STR},
  {MSG_TISK_IGNORE,(STRPTR)MSG_TISK_IGNORE_STR},
  {MSG_TISK_BOUNDED,(STRPTR)MSG_TISK_BOUNDED_STR},
  {MSG_TISK_ABSOLUTE,(STRPTR)MSG_TISK_ABSOLUTE_STR},
  {MSG_TISK_PIXEL,(STRPTR)MSG_TISK_PIXEL_STR},
  {MSG_TISK_MULTIPLY,(STRPTR)MSG_TISK_MULTIPLY_STR},
  {MSG_TISK_ORDERED,(STRPTR)MSG_TISK_ORDERED_STR},
  {MSG_TISK_HALFTONE,(STRPTR)MSG_TISK_HALFTONE_STR},
  {MSG_TISK_FLOYDSTEINBERG,(STRPTR)MSG_TISK_FLOYDSTEINBERG_STR},
  {0,NULL}
};

#endif /* CATCOMP_ARRAY */

/***************************************************************/

#ifdef CATCOMP_BLOCK

#error CATCOMP_BLOCK not supported by this SD

#endif /* CATCOMP_BLOCK */

/***************************************************************/

#ifdef CATCOMP_CODE

#error CATCOMP_CODE not supported by this SD

#endif /* CATCOMP_CODE */

/***************************************************************/


#endif /* PRINTER_STRINGS_H */
