/****************************************************************
   This file was created automatically by `FlexCat 2.19'
   from "/home/willem/ApolloOS/workbench/libs/muimaster/catalogs/muimaster.cd".

   Do NOT edit by hand!
****************************************************************/

#ifndef MUIMASTER_STRINGS_H
#define MUIMASTER_STRINGS_H


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif


#ifdef CATCOMP_ARRAY
#ifndef CATCOMPARRAY
#define CATCOMPARRAY CatCompArray
#endif
#undef CATCOMP_NUMBERS
#undef CATCOMP_STRINGS
#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS
#endif

#ifdef CATCOMP_BLOCK
#undef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif

/***************************************************************/

#ifdef CATCOMP_NUMBERS

#define MSG_OK 0
#define MSG_CANCEL 1
#define MSG_ABOUTMUI_WINDOW_TITLE 2
#define MSG_ABOUTMUI_STRING 3
#define MSG_COLORADJUST_RED 4
#define MSG_COLORADJUST_GREEN 5
#define MSG_COLORADJUST_BLUE 6
#define MSG_DIRLIST_NAME 7
#define MSG_DIRLIST_SIZE 8
#define MSG_DIRLIST_DATE 9
#define MSG_DIRLIST_TIME 10
#define MSG_DIRLIST_FLAGS 11
#define MSG_DIRLIST_COMMENT 12
#define MSG_FRAMEADJUST_INNER_SPACING 13
#define MSG_FRAMEADJUST_LEFT 14
#define MSG_FRAMEADJUST_TOP 15
#define MSG_FRAMEADJUST_RIGHT 16
#define MSG_FRAMEADJUST_BOTTOM 17
#define MSG_IMAGEADJUST_PATTERN 18
#define MSG_IMAGEADJUST_VECTOR 19
#define MSG_IMAGEADJUST_COLOR 20
#define MSG_IMAGEADJUST_EXTERNAL 21
#define MSG_IMAGEADJUST_BITMAP 22
#define MSG_IMAGEADJUST_GRADIENT 23
#define MSG_IMAGEADJUST_SCALED 24
#define MSG_IMAGEADJUST_TILED 25
#define MSG_IMAGEADJUST_TYPE 26
#define MSG_IMAGEADJUST_ANGLE 27
#define MSG_IMAGEADJUST_VERTICAL 28
#define MSG_IMAGEADJUST_HORIZONTAL 29
#define MSG_IMAGEADJUST_COLORS 30
#define MSG_IMAGEADJUST_START_PEN 31
#define MSG_IMAGEADJUST_END_PEN 32
#define MSG_IMAGEADJUST_PREVIEW 33
#define MSG_PALETTE_COLOR 34
#define MSG_PENADJUST_MUI 35
#define MSG_PENADJUST_COLORMAP 36
#define MSG_PENADJUST_RGB 37
#define MSG_PENADJUST_SHINE 38
#define MSG_PENADJUST_HALFSHINE 39
#define MSG_PENADJUST_BACKGROUND 40
#define MSG_PENADJUST_HALFSHADOW 41
#define MSG_PENADJUST_SHADOW 42
#define MSG_PENADJUST_TEXT 43
#define MSG_PENADJUST_FILL 44
#define MSG_PENADJUST_MARK 45
#define MSG_VOLUMELIST_NAME 46
#define MSG_VOLUMELIST_FULL 47
#define MSG_VOLUMELIST_FREE 48
#define MSG_VOLUMELIST_USED 49

#endif /* CATCOMP_NUMBERS */

/***************************************************************/

#ifdef CATCOMP_STRINGS

#define MSG_OK_STR "_Ok"
#define MSG_CANCEL_STR "_Cancel"
#define MSG_ABOUTMUI_WINDOW_TITLE_STR "About Zune"
#define MSG_ABOUTMUI_STRING_STR "Zune, a MUI clone\n\n"\
	"Compiled on %s\n"\
	"Copyright (C) 2002-2020, The AROS Development Team."
#define MSG_COLORADJUST_RED_STR "Red:"
#define MSG_COLORADJUST_GREEN_STR "Green:"
#define MSG_COLORADJUST_BLUE_STR "Blue:"
#define MSG_DIRLIST_NAME_STR "Name"
#define MSG_DIRLIST_SIZE_STR "Size"
#define MSG_DIRLIST_DATE_STR "Date"
#define MSG_DIRLIST_TIME_STR "Time"
#define MSG_DIRLIST_FLAGS_STR "Flags"
#define MSG_DIRLIST_COMMENT_STR "Comment"
#define MSG_FRAMEADJUST_INNER_SPACING_STR "Inner Spacing:"
#define MSG_FRAMEADJUST_LEFT_STR "Left"
#define MSG_FRAMEADJUST_TOP_STR "Top"
#define MSG_FRAMEADJUST_RIGHT_STR "Right"
#define MSG_FRAMEADJUST_BOTTOM_STR "Bottom"
#define MSG_IMAGEADJUST_PATTERN_STR "Pattern"
#define MSG_IMAGEADJUST_VECTOR_STR "Vector"
#define MSG_IMAGEADJUST_COLOR_STR "Color"
#define MSG_IMAGEADJUST_EXTERNAL_STR "External"
#define MSG_IMAGEADJUST_BITMAP_STR "Bitmap"
#define MSG_IMAGEADJUST_GRADIENT_STR "Gradient"
#define MSG_IMAGEADJUST_SCALED_STR "Scaled"
#define MSG_IMAGEADJUST_TILED_STR "Tiled"
#define MSG_IMAGEADJUST_TYPE_STR "Type:"
#define MSG_IMAGEADJUST_ANGLE_STR "Angle:"
#define MSG_IMAGEADJUST_VERTICAL_STR "Vertical"
#define MSG_IMAGEADJUST_HORIZONTAL_STR "Horizontal"
#define MSG_IMAGEADJUST_COLORS_STR "Colors:"
#define MSG_IMAGEADJUST_START_PEN_STR "Start pen"
#define MSG_IMAGEADJUST_END_PEN_STR "End pen"
#define MSG_IMAGEADJUST_PREVIEW_STR "Preview:"
#define MSG_PALETTE_COLOR_STR "Color %ld"
#define MSG_PENADJUST_MUI_STR "MUI"
#define MSG_PENADJUST_COLORMAP_STR "Colormap"
#define MSG_PENADJUST_RGB_STR "RGB"
#define MSG_PENADJUST_SHINE_STR "Shine"
#define MSG_PENADJUST_HALFSHINE_STR "Halfshine"
#define MSG_PENADJUST_BACKGROUND_STR "Background"
#define MSG_PENADJUST_HALFSHADOW_STR "Halfshadow"
#define MSG_PENADJUST_SHADOW_STR "Shadow"
#define MSG_PENADJUST_TEXT_STR "Text"
#define MSG_PENADJUST_FILL_STR "Fill"
#define MSG_PENADJUST_MARK_STR "Mark"
#define MSG_VOLUMELIST_NAME_STR "Name"
#define MSG_VOLUMELIST_FULL_STR "Full"
#define MSG_VOLUMELIST_FREE_STR "Free"
#define MSG_VOLUMELIST_USED_STR "Used"

#endif /* CATCOMP_STRINGS */

/***************************************************************/

#ifdef CATCOMP_ARRAY

#ifndef HAVE_CATCOMP_ARRAYTYPE
#define HAVE_CATCOMP_ARRAYTYPE
struct CatCompArrayType
{
  IPTR   cca_ID;
  STRPTR cca_Str;
};
#endif

static const struct CatCompArrayType CATCOMPARRAY[] =
{
  {MSG_OK,(STRPTR)MSG_OK_STR},
  {MSG_CANCEL,(STRPTR)MSG_CANCEL_STR},
  {MSG_ABOUTMUI_WINDOW_TITLE,(STRPTR)MSG_ABOUTMUI_WINDOW_TITLE_STR},
  {MSG_ABOUTMUI_STRING,(STRPTR)MSG_ABOUTMUI_STRING_STR},
  {MSG_COLORADJUST_RED,(STRPTR)MSG_COLORADJUST_RED_STR},
  {MSG_COLORADJUST_GREEN,(STRPTR)MSG_COLORADJUST_GREEN_STR},
  {MSG_COLORADJUST_BLUE,(STRPTR)MSG_COLORADJUST_BLUE_STR},
  {MSG_DIRLIST_NAME,(STRPTR)MSG_DIRLIST_NAME_STR},
  {MSG_DIRLIST_SIZE,(STRPTR)MSG_DIRLIST_SIZE_STR},
  {MSG_DIRLIST_DATE,(STRPTR)MSG_DIRLIST_DATE_STR},
  {MSG_DIRLIST_TIME,(STRPTR)MSG_DIRLIST_TIME_STR},
  {MSG_DIRLIST_FLAGS,(STRPTR)MSG_DIRLIST_FLAGS_STR},
  {MSG_DIRLIST_COMMENT,(STRPTR)MSG_DIRLIST_COMMENT_STR},
  {MSG_FRAMEADJUST_INNER_SPACING,(STRPTR)MSG_FRAMEADJUST_INNER_SPACING_STR},
  {MSG_FRAMEADJUST_LEFT,(STRPTR)MSG_FRAMEADJUST_LEFT_STR},
  {MSG_FRAMEADJUST_TOP,(STRPTR)MSG_FRAMEADJUST_TOP_STR},
  {MSG_FRAMEADJUST_RIGHT,(STRPTR)MSG_FRAMEADJUST_RIGHT_STR},
  {MSG_FRAMEADJUST_BOTTOM,(STRPTR)MSG_FRAMEADJUST_BOTTOM_STR},
  {MSG_IMAGEADJUST_PATTERN,(STRPTR)MSG_IMAGEADJUST_PATTERN_STR},
  {MSG_IMAGEADJUST_VECTOR,(STRPTR)MSG_IMAGEADJUST_VECTOR_STR},
  {MSG_IMAGEADJUST_COLOR,(STRPTR)MSG_IMAGEADJUST_COLOR_STR},
  {MSG_IMAGEADJUST_EXTERNAL,(STRPTR)MSG_IMAGEADJUST_EXTERNAL_STR},
  {MSG_IMAGEADJUST_BITMAP,(STRPTR)MSG_IMAGEADJUST_BITMAP_STR},
  {MSG_IMAGEADJUST_GRADIENT,(STRPTR)MSG_IMAGEADJUST_GRADIENT_STR},
  {MSG_IMAGEADJUST_SCALED,(STRPTR)MSG_IMAGEADJUST_SCALED_STR},
  {MSG_IMAGEADJUST_TILED,(STRPTR)MSG_IMAGEADJUST_TILED_STR},
  {MSG_IMAGEADJUST_TYPE,(STRPTR)MSG_IMAGEADJUST_TYPE_STR},
  {MSG_IMAGEADJUST_ANGLE,(STRPTR)MSG_IMAGEADJUST_ANGLE_STR},
  {MSG_IMAGEADJUST_VERTICAL,(STRPTR)MSG_IMAGEADJUST_VERTICAL_STR},
  {MSG_IMAGEADJUST_HORIZONTAL,(STRPTR)MSG_IMAGEADJUST_HORIZONTAL_STR},
  {MSG_IMAGEADJUST_COLORS,(STRPTR)MSG_IMAGEADJUST_COLORS_STR},
  {MSG_IMAGEADJUST_START_PEN,(STRPTR)MSG_IMAGEADJUST_START_PEN_STR},
  {MSG_IMAGEADJUST_END_PEN,(STRPTR)MSG_IMAGEADJUST_END_PEN_STR},
  {MSG_IMAGEADJUST_PREVIEW,(STRPTR)MSG_IMAGEADJUST_PREVIEW_STR},
  {MSG_PALETTE_COLOR,(STRPTR)MSG_PALETTE_COLOR_STR},
  {MSG_PENADJUST_MUI,(STRPTR)MSG_PENADJUST_MUI_STR},
  {MSG_PENADJUST_COLORMAP,(STRPTR)MSG_PENADJUST_COLORMAP_STR},
  {MSG_PENADJUST_RGB,(STRPTR)MSG_PENADJUST_RGB_STR},
  {MSG_PENADJUST_SHINE,(STRPTR)MSG_PENADJUST_SHINE_STR},
  {MSG_PENADJUST_HALFSHINE,(STRPTR)MSG_PENADJUST_HALFSHINE_STR},
  {MSG_PENADJUST_BACKGROUND,(STRPTR)MSG_PENADJUST_BACKGROUND_STR},
  {MSG_PENADJUST_HALFSHADOW,(STRPTR)MSG_PENADJUST_HALFSHADOW_STR},
  {MSG_PENADJUST_SHADOW,(STRPTR)MSG_PENADJUST_SHADOW_STR},
  {MSG_PENADJUST_TEXT,(STRPTR)MSG_PENADJUST_TEXT_STR},
  {MSG_PENADJUST_FILL,(STRPTR)MSG_PENADJUST_FILL_STR},
  {MSG_PENADJUST_MARK,(STRPTR)MSG_PENADJUST_MARK_STR},
  {MSG_VOLUMELIST_NAME,(STRPTR)MSG_VOLUMELIST_NAME_STR},
  {MSG_VOLUMELIST_FULL,(STRPTR)MSG_VOLUMELIST_FULL_STR},
  {MSG_VOLUMELIST_FREE,(STRPTR)MSG_VOLUMELIST_FREE_STR},
  {MSG_VOLUMELIST_USED,(STRPTR)MSG_VOLUMELIST_USED_STR},
  {0,NULL}
};

#endif /* CATCOMP_ARRAY */

/***************************************************************/

#ifdef CATCOMP_BLOCK

#error CATCOMP_BLOCK not supported by this SD

#endif /* CATCOMP_BLOCK */

/***************************************************************/

#ifdef CATCOMP_CODE

#error CATCOMP_CODE not supported by this SD

#endif /* CATCOMP_CODE */

/***************************************************************/


#endif /* MUIMASTER_STRINGS_H */
